version: "3.9"

services:
  # runtime image built from your Dockerfile (multi-stage)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sll-reverse-between:latest
    container_name: sll-reverse-between
    restart: "no"
    # runtime command from your Dockerfile will be used
    ports: []          # add ports if your app listens on any
    depends_on: []
    profiles: []

  # test service: runs Gradle tests using containerized gradle
  test:
    image: gradle:9.0.0-jdk24
    container_name: sll-reverse-between-test
    working_dir: /home/gradle/project
    volumes:
      - ./:/home/gradle/project:cached
    entrypoint: ["/bin/sh", "-c"]
    command: >
      ./gradlew --no-daemon clean test --stacktrace --info --no-build-cache --console=plain
    restart: "no"
