plugins {
    id 'java'
    id 'application'
}

group = 'com.jk.explore'
version = '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.jk.explore.singlylinkedlistrecursive.RecursiveSinglyLinkedListDemo'
}

test {
    useJUnitPlatform()
}
